import { Achievement } from '@/types/achievements';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_steps',
    name: 'First Steps',
    description: 'Complete your first floor',
    icon: '🎯',
    requirement: 1,
    unlocked: false,
    progress: 0,
    category: 'floors',
    rarity: 'common',
  },
  {
    id: 'floor_master',
    name: 'Floor Master',
    description: 'Complete 10 floors',
    icon: '🏆',
    requirement: 10,
    unlocked: false,
    progress: 0,
    category: 'floors',
    rarity: 'rare',
  },
  {
    id: 'floor_legend',
    name: 'Floor Legend',
    description: 'Complete 50 floors',
    icon: '👑',
    requirement: 50,
    unlocked: false,
    progress: 0,
    category: 'floors',
    rarity: 'epic',
  },
  {
    id: 'perfectionist',
    name: 'Perfectionist',
    description: 'Complete a floor without any mistakes',
    icon: '✨',
    requirement: 1,
    unlocked: false,
    progress: 0,
    category: 'perfect',
    rarity: 'rare',
  },
  {
    id: 'flawless_master',
    name: 'Flawless Master',
    description: 'Complete 5 floors without any mistakes',
    icon: '💎',
    requirement: 5,
    unlocked: false,
    progress: 0,
    category: 'perfect',
    rarity: 'epic',
  },
  {
    id: 'rich_collector',
    name: 'Rich Collector',
    description: 'Earn 1000 total currency',
    icon: '💰',
    requirement: 1000,
    unlocked: false,
    progress: 0,
    category: 'currency',
    rarity: 'rare',
  },
  {
    id: 'upgrade_addict',
    name: 'Upgrade Addict',
    description: 'Purchase 20 upgrades',
    icon: '🎁',
    requirement: 20,
    unlocked: false,
    progress: 0,
    category: 'upgrades',
    rarity: 'rare',
  },
  {
    id: 'speed_runner',
    name: 'Speed Runner',
    description: 'Complete a floor in under 2 minutes',
    icon: '⚡',
    requirement: 120,
    unlocked: false,
    progress: 0,
    category: 'speed',
    rarity: 'epic',
  },
  {
    id: 'survivor',
    name: 'Survivor',
    description: 'Reach floor 5',
    icon: '🛡️',
    requirement: 5,
    unlocked: false,
    progress: 0,
    category: 'survival',
    rarity: 'rare',
  },
  {
    id: 'victory_first',
    name: 'First Victory',
    description: 'Win your first game',
    icon: '🎊',
    requirement: 1,
    unlocked: false,
    progress: 0,
    category: 'survival',
    rarity: 'epic',
  },
  {
    id: 'win_streak',
    name: 'On Fire',
    description: 'Win 3 games in a row',
    icon: '🔥',
    requirement: 3,
    unlocked: false,
    progress: 0,
    category: 'survival',
    rarity: 'legendary',
  },
  {
    id: 'mistake_free',
    name: 'Untouchable',
    description: 'Win a game without making any mistakes',
    icon: '🌟',
    requirement: 1,
    unlocked: false,
    progress: 0,
    category: 'perfect',
    rarity: 'legendary',
  },
];
