import { ShopOffer } from '@/types/shop';

export const NUMBER_UPGRADES: ShopOffer[] = [
  {
    id: 'num_1_t1',
    type: 'NumberUpgrade',
    digit: 1,
    tier: 1,
    rarity: 'Common',
    baseCostOF: 40,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Placing 1s reveals one random cell',
    descriptionFull: 'Each time you correctly place a 1, one random empty cell on the board is revealed with its correct value.',
    entropyDrainPerFloor: 0,
    weight: 70,
    effect: 'reveal_cell',
  },
  {
    id: 'num_1_t2',
    type: 'NumberUpgrade',
    digit: 1,
    tier: 2,
    rarity: 'Uncommon',
    baseCostOF: 140,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Placing 1s reveals two cells',
    descriptionFull: 'Each time you correctly place a 1, two random empty cells are revealed.',
    entropyDrainPerFloor: 0,
    dependency: 'num_1_t1',
    weight: 25,
    effect: 'reveal_cell_2',
  },
  {
    id: 'num_3_t1',
    type: 'NumberUpgrade',
    digit: 3,
    tier: 1,
    rarity: 'Common',
    baseCostOF: 60,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: '3s show hints for adjacent cells',
    descriptionFull: 'When you place a 3 correctly, adjacent cells (up/down/left/right) reveal their correct candidates.',
    entropyDrainPerFloor: 0,
    weight: 70,
    effect: 'hint_adjacent',
  },
  {
    id: 'num_3_t2',
    type: 'NumberUpgrade',
    digit: 3,
    tier: 2,
    rarity: 'Rare',
    baseCostOF: 180,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: '3s auto-fill adjacent cells',
    descriptionFull: 'When you place a 3 correctly, adjacent empty cells are automatically filled with their correct values.',
    entropyDrainPerFloor: 1,
    dependency: 'num_3_t1',
    weight: 5,
    effect: 'fill_adjacent',
  },
  {
    id: 'num_5_t1',
    type: 'NumberUpgrade',
    digit: 5,
    tier: 1,
    rarity: 'Common',
    baseCostOF: 50,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Placing 5s reduces corruption by 3',
    descriptionFull: 'Each correctly placed 5 reduces global corruption by 3 points.',
    entropyDrainPerFloor: 0,
    weight: 70,
    effect: 'corruption_reduction',
  },
  {
    id: 'num_5_t2',
    type: 'NumberUpgrade',
    digit: 5,
    tier: 2,
    rarity: 'Uncommon',
    baseCostOF: 140,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Placing 5s reduces corruption by 5 and cleanses 2 cells',
    descriptionFull: 'Each correctly placed 5 reduces global corruption by 5 and cleanses the 2 most corrupted cells.',
    entropyDrainPerFloor: 0,
    dependency: 'num_5_t1',
    weight: 25,
    effect: 'corruption_cleanse',
  },
  {
    id: 'num_7_t1',
    type: 'NumberUpgrade',
    digit: 7,
    tier: 1,
    rarity: 'Common',
    baseCostOF: 50,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Placing 7s gives +5 OF',
    descriptionFull: 'Each correctly placed 7 grants 5 Order Fragments immediately.',
    entropyDrainPerFloor: 0,
    weight: 70,
    effect: 'currency_bonus_5',
  },
  {
    id: 'num_7_t2',
    type: 'NumberUpgrade',
    digit: 7,
    tier: 2,
    rarity: 'Uncommon',
    baseCostOF: 120,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Placing 7s gives +10 OF',
    descriptionFull: 'Each correctly placed 7 grants 10 Order Fragments immediately.',
    entropyDrainPerFloor: 0,
    dependency: 'num_7_t1',
    weight: 25,
    effect: 'currency_bonus_10',
  },
  {
    id: 'num_9_t1',
    type: 'NumberUpgrade',
    digit: 9,
    tier: 1,
    rarity: 'Rare',
    baseCostOF: 150,
    baseCostED: 5,
    runLimited: true,
    descriptionShort: 'All 9 nines clear all corruption',
    descriptionFull: 'When you correctly place all nine 9s on the board, all corruption is cleared instantly.',
    entropyDrainPerFloor: 0,
    weight: 5,
    effect: 'corruption_clear',
  },
];

export const RELICS_PERMANENT: ShopOffer[] = [
  {
    id: 'perm_double_starter',
    type: 'RelicPermanent',
    rarity: 'Rare',
    baseCostOF: 800,
    baseCostED: 0,
    runLimited: false,
    descriptionShort: 'Start each run with 200 OF',
    descriptionFull: 'Permanently increases your starting Order Fragments from 100 to 200 for all future runs.',
    entropyDrainPerFloor: 0,
    weight: 5,
    effect: 'starter_bonus',
  },
  {
    id: 'perm_ed_starter',
    type: 'RelicPermanent',
    rarity: 'Rare',
    baseCostOF: 600,
    baseCostED: 0,
    runLimited: false,
    descriptionShort: 'Start each run with 10 ED',
    descriptionFull: 'Permanently grants 10 Entropy Dust at the start of every run.',
    entropyDrainPerFloor: 0,
    weight: 5,
    effect: 'ed_starter',
  },
];

export const RELICS_RUN: ShopOffer[] = [
  {
    id: 'run_mistake_insurance',
    type: 'RelicRun',
    rarity: 'Common',
    baseCostOF: 80,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: '+2 maximum mistakes',
    descriptionFull: 'Increases your maximum mistakes by 2 for this run.',
    entropyDrainPerFloor: 0,
    weight: 70,
    effect: 'max_mistakes',
  },
  {
    id: 'run_corruption_shield',
    type: 'RelicRun',
    rarity: 'Uncommon',
    baseCostOF: 120,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Mistakes generate 50% less corruption',
    descriptionFull: 'All corruption generated from mistakes is reduced by 50% for this run.',
    entropyDrainPerFloor: 0,
    weight: 25,
    effect: 'corruption_resist',
  },
  {
    id: 'run_golden_touch',
    type: 'RelicRun',
    rarity: 'Common',
    baseCostOF: 90,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Earn 2x OF from floor completion',
    descriptionFull: 'Doubles the Order Fragments earned from completing floors for this run.',
    entropyDrainPerFloor: 0,
    weight: 70,
    effect: 'currency_multiplier',
  },
  {
    id: 'run_corruption_barrier',
    type: 'RelicRun',
    rarity: 'Rare',
    baseCostOF: 180,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Corruption cannot spread',
    descriptionFull: 'Prevents corruption from spreading to adjacent cells for this run.',
    entropyDrainPerFloor: 1,
    weight: 5,
    effect: 'no_spread',
  },
  {
    id: 'run_decay_immunity',
    type: 'RelicRun',
    rarity: 'Uncommon',
    baseCostOF: 100,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Corruption degradation reduced by 75%',
    descriptionFull: 'Reduces the effects of corruption degradation by 75% for this run.',
    entropyDrainPerFloor: 0,
    weight: 25,
    effect: 'degradation_resist',
  },
];

export const CONSUMABLES: ShopOffer[] = [
  {
    id: 'cons_insight_marker',
    type: 'Consumable',
    rarity: 'Common',
    baseCostOF: 30,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Mark one ambiguous cell for 50% corruption reduction',
    descriptionFull: 'Mark one ambiguous tile. If your guess is wrong, corruption penalty is reduced by 50%.',
    entropyDrainPerFloor: 0,
    weight: 70,
    effect: 'ambiguity_hedge',
  },
  {
    id: 'cons_truth_beacon',
    type: 'Consumable',
    rarity: 'Uncommon',
    baseCostOF: 70,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Resolve one ambiguous zone',
    descriptionFull: 'Reveals the correct values for one ambiguous zone on the current floor.',
    entropyDrainPerFloor: 0,
    weight: 25,
    effect: 'ambiguity_resolve',
  },
  {
    id: 'cons_purification',
    type: 'Consumable',
    rarity: 'Uncommon',
    baseCostOF: 60,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Cleanse 5 most corrupted cells',
    descriptionFull: 'Immediately cleanses the 5 most corrupted cells on the board.',
    entropyDrainPerFloor: 0,
    weight: 25,
    effect: 'cleanse_cells',
  },
  {
    id: 'cons_entropy_lens',
    type: 'Consumable',
    rarity: 'Common',
    baseCostOF: 40,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Highlights ambiguous zones for this floor',
    descriptionFull: 'Highlights all ambiguous zones on the current floor without revealing solutions.',
    entropyDrainPerFloor: 0,
    weight: 70,
    effect: 'ambiguity_detect',
  },
  {
    id: 'cons_logic_anchor',
    type: 'Consumable',
    rarity: 'Rare',
    baseCostOF: 100,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Make one row or column ambiguity-free',
    descriptionFull: 'Locks one row or column into unique-solution mode, eliminating all ambiguity in that region.',
    entropyDrainPerFloor: 0,
    weight: 5,
    effect: 'ambiguity_suppress',
  },
  {
    id: 'cons_divergence_charm',
    type: 'Consumable',
    rarity: 'Uncommon',
    baseCostOF: 80,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Contains ambiguity corruption to single cell',
    descriptionFull: 'If you guess wrong in an ambiguous area, corruption only affects that single cell.',
    entropyDrainPerFloor: 0,
    weight: 25,
    effect: 'ambiguity_contain',
  },
  {
    id: 'cons_emergency',
    type: 'Consumable',
    rarity: 'Common',
    baseCostOF: 10,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Reveals 1 random cell',
    descriptionFull: 'Emergency consumable. Reveals one random empty cell with its correct value.',
    entropyDrainPerFloor: 0,
    weight: 70,
    effect: 'reveal_one',
  },
];

export const RULE_MUTATORS: ShopOffer[] = [
  {
    id: 'mut_vision_boost',
    type: 'RuleMutator',
    rarity: 'Common',
    baseCostOF: 20,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Fog effects reduced by 50% next floor',
    descriptionFull: 'Reduces the intensity of fog modifiers by 50% on the next floor.',
    entropyDrainPerFloor: 0,
    weight: 70,
    effect: 'reduce_fog',
  },
  {
    id: 'mut_validation_faster',
    type: 'RuleMutator',
    rarity: 'Common',
    baseCostOF: 30,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Delayed validation reduced by 1 move',
    descriptionFull: 'Reduces the delayed validation window by 1 move on the next floor.',
    entropyDrainPerFloor: 0,
    weight: 70,
    effect: 'faster_validation',
  },
  {
    id: 'mut_corruption_slower',
    type: 'RuleMutator',
    rarity: 'Uncommon',
    baseCostOF: 50,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Corruption spread slowed by 50% next floor',
    descriptionFull: 'Reduces corruption spread chance by 50% on the next floor.',
    entropyDrainPerFloor: 0,
    weight: 25,
    effect: 'slow_corruption',
  },
];

export const RARITY_WEIGHTS = {
  Common: 70,
  Uncommon: 25,
  Rare: 5,
};
