import { ShopOffer } from '@/types/shop';

export const NUMBER_UPGRADES: ShopOffer[] = [
  {
    id: 'num_1_t1',
    type: 'NumberUpgrade',
    digit: 1,
    tier: 1,
    rarity: 'Common',
    baseCostOF: 40,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Placing 1s reveals one random cell',
    descriptionFull: 'Each time you correctly place a 1, one random empty cell on the board is revealed with its correct value.',
    entropyDrainPerFloor: 0,
    weight: 70,
    effect: 'reveal_cell',
  },
  {
    id: 'num_1_t2',
    type: 'NumberUpgrade',
    digit: 1,
    tier: 2,
    rarity: 'Uncommon',
    baseCostOF: 140,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Placing 1s reveals two cells',
    descriptionFull: 'Each time you correctly place a 1, two random empty cells are revealed.',
    entropyDrainPerFloor: 0,
    dependency: 'num_1_t1',
    weight: 25,
    effect: 'reveal_cell_2',
  },
  {
    id: 'num_3_t1',
    type: 'NumberUpgrade',
    digit: 3,
    tier: 1,
    rarity: 'Common',
    baseCostOF: 60,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: '3s show hints for adjacent cells',
    descriptionFull: 'When you place a 3 correctly, adjacent cells (up/down/left/right) reveal their correct candidates.',
    entropyDrainPerFloor: 0,
    weight: 70,
    effect: 'hint_adjacent',
  },
  {
    id: 'num_3_t2',
    type: 'NumberUpgrade',
    digit: 3,
    tier: 2,
    rarity: 'Rare',
    baseCostOF: 180,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: '3s auto-fill adjacent cells',
    descriptionFull: 'When you place a 3 correctly, adjacent empty cells are automatically filled with their correct values.',
    entropyDrainPerFloor: 1,
    dependency: 'num_3_t1',
    weight: 5,
    effect: 'fill_adjacent',
  },
  {
    id: 'num_5_t1',
    type: 'NumberUpgrade',
    digit: 5,
    tier: 1,
    rarity: 'Common',
    baseCostOF: 50,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Placing 5s reduces corruption by 3',
    descriptionFull: 'Each correctly placed 5 reduces global corruption by 3 points.',
    entropyDrainPerFloor: 0,
    weight: 70,
    effect: 'corruption_reduction',
  },
  {
    id: 'num_5_t2',
    type: 'NumberUpgrade',
    digit: 5,
    tier: 2,
    rarity: 'Uncommon',
    baseCostOF: 140,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Placing 5s reduces corruption by 5 and cleanses 2 cells',
    descriptionFull: 'Each correctly placed 5 reduces global corruption by 5 and cleanses the 2 most corrupted cells.',
    entropyDrainPerFloor: 0,
    dependency: 'num_5_t1',
    weight: 25,
    effect: 'corruption_cleanse',
  },
  {
    id: 'num_7_t1',
    type: 'NumberUpgrade',
    digit: 7,
    tier: 1,
    rarity: 'Common',
    baseCostOF: 50,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Placing 7s gives +5 OF',
    descriptionFull: 'Each correctly placed 7 grants 5 Order Fragments immediately.',
    entropyDrainPerFloor: 0,
    weight: 70,
    effect: 'currency_bonus_5',
  },
  {
    id: 'num_7_t2',
    type: 'NumberUpgrade',
    digit: 7,
    tier: 2,
    rarity: 'Uncommon',
    baseCostOF: 120,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Placing 7s gives +10 OF',
    descriptionFull: 'Each correctly placed 7 grants 10 Order Fragments immediately.',
    entropyDrainPerFloor: 0,
    dependency: 'num_7_t1',
    weight: 25,
    effect: 'currency_bonus_10',
  },
  {
    id: 'num_9_t1',
    type: 'NumberUpgrade',
    digit: 9,
    tier: 1,
    rarity: 'Rare',
    baseCostOF: 150,
    baseCostED: 5,
    runLimited: true,
    descriptionShort: 'All 9 nines clear all corruption',
    descriptionFull: 'When you correctly place all nine 9s on the board, all corruption is cleared instantly.',
    entropyDrainPerFloor: 0,
    weight: 5,
    effect: 'corruption_clear',
  },
];

export const RELICS_PERMANENT: ShopOffer[] = [
  {
    id: 'perm_double_starter',
    type: 'RelicPermanent',
    rarity: 'Rare',
    baseCostOF: 800,
    baseCostED: 0,
    runLimited: false,
    descriptionShort: 'Wealthy Beginning',
    descriptionFull: 'Permanently increases your starting Order Fragments from 100 to 200 for all future runs.',
    entropyDrainPerFloor: 0,
    weight: 5,
    effect: 'starter_bonus',
  },
  {
    id: 'perm_ed_starter',
    type: 'RelicPermanent',
    rarity: 'Rare',
    baseCostOF: 600,
    baseCostED: 0,
    runLimited: false,
    descriptionShort: 'Entropy Catalyst',
    descriptionFull: 'Permanently grants 10 Entropy Dust at the start of every run.',
    entropyDrainPerFloor: 0,
    weight: 5,
    effect: 'ed_starter',
  },
];

export const ARTIFACTS: ShopOffer[] = [
  {
    id: 'art_corrupted_core',
    type: 'RelicRun',
    rarity: 'Rare',
    baseCostOF: 200,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Corrupted Core',
    descriptionFull: 'Gain +10 Gold every time you make a Mistake, but Corruption Spread from mistakes is doubled.',
    entropyDrainPerFloor: 0,
    weight: 5,
    effect: 'corrupt_gold',
  },
  {
    id: 'art_auto_penciler',
    type: 'RelicRun',
    rarity: 'Rare',
    baseCostOF: 150,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Auto-Penciler',
    descriptionFull: 'At the start of every puzzle, all cells are automatically filled with all their possible candidates.',
    entropyDrainPerFloor: 0,
    weight: 5,
    effect: 'auto_candidates',
  },
  {
    id: 'art_reinforced_buffer',
    type: 'RelicRun',
    rarity: 'Rare',
    baseCostOF: 250,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Reinforced Buffer',
    descriptionFull: 'Increases your permanent Mistake Buffer by +1.',
    entropyDrainPerFloor: 0,
    weight: 5,
    effect: 'max_mistakes',
  },
  {
    id: 'art_golden_die',
    type: 'RelicRun',
    rarity: 'Uncommon',
    baseCostOF: 80,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Golden Die',
    descriptionFull: 'One number (1-9) is chosen at random. Every time you place that number, you gain +1 Gold.',
    entropyDrainPerFloor: 0,
    weight: 25,
    effect: 'golden_number',
  },
  {
    id: 'art_oracles_compass',
    type: 'RelicRun',
    rarity: 'Rare',
    baseCostOF: 180,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: "Oracle's Compass",
    descriptionFull: 'When you place a number in a 2-3 candidate cell, it shows Red (Wrong) or Green (Right) for 1s, then removes the number. No penalty.',
    entropyDrainPerFloor: 0,
    weight: 5,
    effect: 'guess_preview',
  },
  {
    id: 'art_hazmat_suit',
    type: 'RelicRun',
    rarity: 'Rare',
    baseCostOF: 150,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Hazmat Suit',
    descriptionFull: 'The first Mistake you make in any new puzzle does not cause any Corruption Spread.',
    entropyDrainPerFloor: 0,
    weight: 5,
    effect: 'first_mistake_safe',
  },
  {
    id: 'art_rulebook',
    type: 'RelicRun',
    rarity: 'Rare',
    baseCostOF: 150,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'The Rulebook',
    descriptionFull: 'At the start of a puzzle with a Rule Modifier, you can Veto it once per shop visit.',
    entropyDrainPerFloor: 0,
    weight: 5,
    effect: 'veto_modifier',
  },
];

export const SERVICES: ShopOffer[] = [
  {
    id: 'serv_system_cleanse',
    type: 'RuleMutator',
    rarity: 'Rare',
    baseCostOF: 150,
    baseCostED: 0,
    runLimited: false,
    descriptionShort: 'System Cleanse',
    descriptionFull: 'Instantly removes all current Corruption Inflation for this shop visit, resetting all item prices to base cost.',
    entropyDrainPerFloor: 0,
    weight: 5,
    effect: 'cleanse_inflation',
  },
];

export const CONSUMABLES: ShopOffer[] = [
  {
    id: 'cons_glimmercap',
    type: 'Consumable',
    rarity: 'Common',
    baseCostOF: 30,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Glimmercap',
    descriptionFull: 'Instantly clears all Fog and Phantom Candidates from the entire board.',
    entropyDrainPerFloor: 0,
    weight: 70,
    effect: 'clear_fog',
  },
  {
    id: 'cons_aegis_charm',
    type: 'Consumable',
    rarity: 'Uncommon',
    baseCostOF: 50,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Aegis Charm',
    descriptionFull: 'You start the next puzzle with one Shield. It is consumed on your first mistake.',
    entropyDrainPerFloor: 0,
    weight: 25,
    effect: 'shield_next',
  },
  {
    id: 'cons_purifying_salt',
    type: 'Consumable',
    rarity: 'Uncommon',
    baseCostOF: 50,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Purifying Salt',
    descriptionFull: 'Target a 3x3 box. Cleanse all Corrupted cells within it.',
    entropyDrainPerFloor: 0,
    weight: 25,
    effect: 'cleanse_box',
  },
  {
    id: 'cons_logical_leap',
    type: 'Consumable',
    rarity: 'Rare',
    baseCostOF: 70,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Logical Leap',
    descriptionFull: 'Instantly and correctly solves one random, solvable cell on the board.',
    entropyDrainPerFloor: 0,
    weight: 5,
    effect: 'solve_random',
  },
  {
    id: 'cons_voucher',
    type: 'Consumable',
    rarity: 'Common',
    baseCostOF: 20,
    baseCostED: 0,
    runLimited: true,
    descriptionShort: 'Voucher',
    descriptionFull: 'Automatically gives you a 25% discount on the next single item you purchase in the next shop.',
    entropyDrainPerFloor: 0,
    weight: 70,
    effect: 'discount_next',
  },
];



export const RARITY_WEIGHTS = {
  Common: 70,
  Uncommon: 25,
  Rare: 5,
};
