import { Upgrade } from '@/types/game';

export const UPGRADE_POOL: Upgrade[] = [
  {
    id: 'num_1_l1',
    name: '1 — The Scout [L1]',
    description: 'Find Naked Single: Highlights one random "Naked Single" (an obvious next move)',
    type: 'number',
    number: 1,
    effect: 'scout_find_naked',
    cost: 40,
    rarity: 'common',
  },
  {
    id: 'num_1_l2',
    name: '1 — The Scout [L2]',
    description: 'Fog Clear: Also clears all Fog from its 3x3 box',
    type: 'number',
    number: 1,
    effect: 'scout_fog_clear',
    cost: 120,
    rarity: 'uncommon',
  },
  {
    id: 'num_1_l3',
    name: '1 — The Scout [L3]',
    description: 'Find Hidden Single: Now highlights a "Hidden Single" (more advanced logical move)',
    type: 'number',
    number: 1,
    effect: 'scout_find_hidden',
    cost: 300,
    rarity: 'rare',
  },
  {
    id: 'num_1_l4',
    name: '1 — The Scout [L4]',
    description: 'Solve Single: Automatically solves the "Hidden Single" it finds',
    type: 'number',
    number: 1,
    effect: 'scout_solve_single',
    cost: 500,
    rarity: 'epic',
  },
  {
    id: 'num_1_l5',
    name: '1 — The Scout [L5]',
    description: 'Total Clarity: Solves a Hidden Single, clears Fog from box, reveals Hidden Numbers in row/column',
    type: 'number',
    number: 1,
    effect: 'scout_total_clarity',
    cost: 800,
    rarity: 'epic',
  },
  {
    id: 'num_1_rogue',
    name: '1 — The Scout [ROGUE]',
    description: 'Omniscience: First \'1\' reveals all \'1\'s. Placed \'1\'s disable Fog in adjacent cells',
    type: 'number',
    number: 1,
    effect: 'scout_omniscience',
    cost: 1200,
    rarity: 'rogue',
  },

  {
    id: 'num_2_l1',
    name: '2 — The Merchant [L1]',
    description: 'Investment: Grants +1 Coin',
    type: 'number',
    number: 2,
    effect: 'merchant_gold_1',
    cost: 50,
    rarity: 'common',
  },
  {
    id: 'num_2_l2',
    name: '2 — The Merchant [L2]',
    description: 'Compound Interest: Grants +2 Coins',
    type: 'number',
    number: 2,
    effect: 'merchant_gold_2',
    cost: 140,
    rarity: 'uncommon',
  },
  {
    id: 'num_2_l3',
    name: '2 — The Merchant [L3]',
    description: 'Price Check: Grants +2 Coins and reduces next shop\'s Corruption Inflation by 2% (stacks)',
    type: 'number',
    number: 2,
    effect: 'merchant_price_check',
    cost: 320,
    rarity: 'rare',
  },
  {
    id: 'num_2_l4',
    name: '2 — The Merchant [L4]',
    description: 'Liquid Assets: Grants +3 Coins',
    type: 'number',
    number: 2,
    effect: 'merchant_gold_3',
    cost: 480,
    rarity: 'epic',
  },
  {
    id: 'num_2_l5',
    name: '2 — The Merchant [L5]',
    description: 'Market Crash: Last \'2\' placed resets Corruption Inflation to 0% and grants +20 Coins',
    type: 'number',
    number: 2,
    effect: 'merchant_market_crash',
    cost: 700,
    rarity: 'epic',
  },
  {
    id: 'num_2_rogue',
    name: '2 — The Merchant [ROGUE]',
    description: 'Monopoly: Permanently immune to all Corruption Inflation. All shop prices are always at base cost',
    type: 'number',
    number: 2,
    effect: 'merchant_monopoly',
    cost: 1000,
    rarity: 'rogue',
  },

  {
    id: 'num_3_l1',
    name: '3 — The Jester [L1]',
    description: 'Flow State: (Passive) Immune to Candidate Shuffling',
    type: 'number',
    number: 3,
    effect: 'jester_flow_state',
    cost: 45,
    rarity: 'common',
  },
  {
    id: 'num_3_l2',
    name: '3 — The Jester [L2]',
    description: 'Lockpick: Counts as 1 of 3 required placements to break Cell Lock',
    type: 'number',
    number: 3,
    effect: 'jester_lockpick',
    cost: 130,
    rarity: 'uncommon',
  },
  {
    id: 'num_3_l3',
    name: '3 — The Jester [L3]',
    description: 'Rule of Three: Grants +3 Coins if placed 3rd in its box, row, or column',
    type: 'number',
    number: 3,
    effect: 'jester_rule_of_three',
    cost: 280,
    rarity: 'rare',
  },
  {
    id: 'num_3_l4',
    name: '3 — The Jester [L4]',
    description: 'Unstoppable: Instantly breaks any active Cell Lock',
    type: 'number',
    number: 3,
    effect: 'jester_unstoppable',
    cost: 450,
    rarity: 'epic',
  },
  {
    id: 'num_3_l5',
    name: '3 — The Jester [L5]',
    description: 'Grand Triplet: Rule of Three bonus increased from +3 to +6 Coins',
    type: 'number',
    number: 3,
    effect: 'jester_grand_triplet',
    cost: 650,
    rarity: 'epic',
  },
  {
    id: 'num_3_rogue',
    name: '3 — The Jester [ROGUE]',
    description: 'Master of Flow: Immune to all Flow Disruption. Placing a \'3\' always triggers Grand Triplet',
    type: 'number',
    number: 3,
    effect: 'jester_master_flow',
    cost: 950,
    rarity: 'rogue',
  },

  {
    id: 'num_4_l1',
    name: '4 — The Fortress [L1]',
    description: 'Increases Mistake Buffer (HP) by +1',
    type: 'number',
    number: 4,
    effect: 'fortress_buffer_1',
    cost: 35,
    rarity: 'common',
  },
  {
    id: 'num_4_l2',
    name: '4 — The Fortress [L2]',
    description: 'Shield: Grants a Shield for 15 seconds (absorbs 1 Mistake & effects)',
    type: 'number',
    number: 4,
    effect: 'fortress_shield_15',
    cost: 100,
    rarity: 'uncommon',
  },
  {
    id: 'num_4_l3',
    name: '4 — The Fortress [L3]',
    description: 'Increases Mistake Buffer by +2 (total)',
    type: 'number',
    number: 4,
    effect: 'fortress_buffer_2',
    cost: 240,
    rarity: 'rare',
  },
  {
    id: 'num_4_l4',
    name: '4 — The Fortress [L4]',
    description: 'Reinforce: Shield duration increases to 30 seconds',
    type: 'number',
    number: 4,
    effect: 'fortress_shield_30',
    cost: 400,
    rarity: 'epic',
  },
  {
    id: 'num_4_l5',
    name: '4 — The Fortress [L5]',
    description: 'Start every puzzle with one Shield active',
    type: 'number',
    number: 4,
    effect: 'fortress_start_shield',
    cost: 600,
    rarity: 'epic',
  },
  {
    id: 'num_4_rogue',
    name: '4 — The Fortress [ROGUE]',
    description: 'Absolution: Once per puzzle, your last Mistake is ignored. Buffer resets to 1, and all Corruption is Cleansed',
    type: 'number',
    number: 4,
    effect: 'fortress_absolution',
    cost: 900,
    rarity: 'rogue',
  },

  {
    id: 'num_5_l1',
    name: '5 — The Catalyst [L1]',
    description: 'Ignite: Triggers a random one of your other owned Level 1 abilities',
    type: 'number',
    number: 5,
    effect: 'catalyst_ignite',
    cost: 50,
    rarity: 'common',
  },
  {
    id: 'num_5_l2',
    name: '5 — The Catalyst [L2]',
    description: 'Synergy: Triggers all of your owned Level 1 abilities',
    type: 'number',
    number: 5,
    effect: 'catalyst_synergy',
    cost: 140,
    rarity: 'uncommon',
  },
  {
    id: 'num_5_l3',
    name: '5 — The Catalyst [L3]',
    description: 'Potency: Abilities from L2 trigger as if they are Level 2 (or current level, if higher)',
    type: 'number',
    number: 5,
    effect: 'catalyst_potency',
    cost: 300,
    rarity: 'rare',
  },
  {
    id: 'num_5_l4',
    name: '5 — The Catalyst [L4]',
    description: 'Catalyze: Now also triggers all of your owned Level 3 abilities',
    type: 'number',
    number: 5,
    effect: 'catalyst_catalyze',
    cost: 520,
    rarity: 'epic',
  },
  {
    id: 'num_5_l5',
    name: '5 — The Catalyst [L5]',
    description: 'Fusion: Triggers all abilities (from L2, L4) at their full current level',
    type: 'number',
    number: 5,
    effect: 'catalyst_fusion',
    cost: 750,
    rarity: 'epic',
  },
  {
    id: 'num_5_rogue',
    name: '5 — The Catalyst [ROGUE]',
    description: 'Overclock: All other number abilities (1-4, 6-9) are permanently considered +1 Level (capping at L5)',
    type: 'number',
    number: 5,
    effect: 'catalyst_overclock',
    cost: 1100,
    rarity: 'rogue',
  },

  {
    id: 'num_6_l1',
    name: '6 — The Gambler [L1]',
    description: '50/50: 50% chance to gain +4 Gold',
    type: 'number',
    number: 6,
    effect: 'gambler_fifty_fifty',
    cost: 40,
    rarity: 'common',
  },
  {
    id: 'num_6_l2',
    name: '6 — The Gambler [L2]',
    description: 'Hedge: 50% chance to not trigger Mistake penalty if wrong on a 2-candidate cell',
    type: 'number',
    number: 6,
    effect: 'gambler_hedge',
    cost: 120,
    rarity: 'uncommon',
  },
  {
    id: 'num_6_l3',
    name: '6 — The Gambler [L3]',
    description: 'Tip the Odds: The L2 chance increases to 75%',
    type: 'number',
    number: 6,
    effect: 'gambler_tip_odds',
    cost: 280,
    rarity: 'rare',
  },
  {
    id: 'num_6_l4',
    name: '6 — The Gambler [L4]',
    description: 'Safe Bet: The L2 "Safe Bet" is now 100% guaranteed',
    type: 'number',
    number: 6,
    effect: 'gambler_safe_bet',
    cost: 480,
    rarity: 'epic',
  },
  {
    id: 'num_6_l5',
    name: '6 — The Gambler [L5]',
    description: 'All In: The L4 "Safe Bet" now works on cells with three candidates',
    type: 'number',
    number: 6,
    effect: 'gambler_all_in',
    cost: 700,
    rarity: 'epic',
  },
  {
    id: 'num_6_rogue',
    name: '6 — The Gambler [ROGUE]',
    description: 'Reality Warp: Once per puzzle, if you place a \'6\' in a "multiple-solution state," the game\'s solution conforms to your placement',
    type: 'number',
    number: 6,
    effect: 'gambler_reality_warp',
    cost: 1000,
    rarity: 'rogue',
  },

  {
    id: 'num_7_l1',
    name: '7 — The Sniper [L1]',
    description: 'Grants +1 Shop Reroll per shop',
    type: 'number',
    number: 7,
    effect: 'sniper_reroll_1',
    cost: 50,
    rarity: 'common',
  },
  {
    id: 'num_7_l2',
    name: '7 — The Sniper [L2]',
    description: 'Focus Fire: Highlights one Hidden Single on the board',
    type: 'number',
    number: 7,
    effect: 'sniper_focus_fire',
    cost: 120,
    rarity: 'uncommon',
  },
  {
    id: 'num_7_l3',
    name: '7 — The Sniper [L3]',
    description: 'Takedown: Solves one random Hidden Single on the board',
    type: 'number',
    number: 7,
    effect: 'sniper_takedown',
    cost: 280,
    rarity: 'rare',
  },
  {
    id: 'num_7_l4',
    name: '7 — The Sniper [L4]',
    description: 'Grants +2 Shop Rerolls (total)',
    type: 'number',
    number: 7,
    effect: 'sniper_reroll_2',
    cost: 460,
    rarity: 'epic',
  },
  {
    id: 'num_7_l5',
    name: '7 — The Sniper [L5]',
    description: 'Chain Shot: Solves all Hidden Singles for one random number',
    type: 'number',
    number: 7,
    effect: 'sniper_chain_shot',
    cost: 650,
    rarity: 'epic',
  },
  {
    id: 'num_7_rogue',
    name: '7 — The Sniper [ROGUE]',
    description: 'Domino Effect: When placing a \'7\' solves a cell, any new Singles created are also instantly solved. Chains until no new singles',
    type: 'number',
    number: 7,
    effect: 'sniper_domino',
    cost: 950,
    rarity: 'rogue',
  },

  {
    id: 'num_8_l1',
    name: '8 — The Powerhouse [L1]',
    description: 'Cleanse: Cleanses 1 random Corrupted cell in its 3x3 box',
    type: 'number',
    number: 8,
    effect: 'powerhouse_cleanse_box',
    cost: 45,
    rarity: 'common',
  },
  {
    id: 'num_8_l2',
    name: '8 — The Powerhouse [L2]',
    description: 'Purge: Cleanses all Corrupted cells in its 3x3 box',
    type: 'number',
    number: 8,
    effect: 'powerhouse_purge_box',
    cost: 130,
    rarity: 'uncommon',
  },
  {
    id: 'num_8_l3',
    name: '8 — The Powerhouse [L3]',
    description: 'Purge+: Cleanses all Corrupted cells in its row and column',
    type: 'number',
    number: 8,
    effect: 'powerhouse_purge_rowcol',
    cost: 300,
    rarity: 'rare',
  },
  {
    id: 'num_8_l4',
    name: '8 — The Powerhouse [L4]',
    description: 'Firewall: Cleansed cells are immune to Corruption for 30 seconds',
    type: 'number',
    number: 8,
    effect: 'powerhouse_firewall',
    cost: 500,
    rarity: 'epic',
  },
  {
    id: 'num_8_l5',
    name: '8 — The Powerhouse [L5]',
    description: 'System Restore: Cleanses its row, column, and box. Also triggers all Number 1 (L1-L5) effects',
    type: 'number',
    number: 8,
    effect: 'powerhouse_system_restore',
    cost: 720,
    rarity: 'epic',
  },
  {
    id: 'num_8_rogue',
    name: '8 — The Powerhouse [ROGUE]',
    description: 'Purification: Once per puzzle, placing an \'8\' Cleanses the entire board of all Corruption, Fog, Phantom Candidates, and Cell Locks',
    type: 'number',
    number: 8,
    effect: 'powerhouse_purification',
    cost: 1050,
    rarity: 'rogue',
  },

  {
    id: 'num_9_l1',
    name: '9 — The Finisher [L1]',
    description: 'Bonus: Gain +3 Gold for completing any 3x3 box',
    type: 'number',
    number: 9,
    effect: 'finisher_box_bonus',
    cost: 60,
    rarity: 'common',
  },
  {
    id: 'num_9_l2',
    name: '9 — The Finisher [L2]',
    description: 'Bonus+: Gain +5 Gold for completing any row or column',
    type: 'number',
    number: 9,
    effect: 'finisher_line_bonus',
    cost: 150,
    rarity: 'uncommon',
  },
  {
    id: 'num_9_l3',
    name: '9 — The Finisher [L3]',
    description: 'Momentum: Gain a permanent +1% boost to all Gold gained. Stacks every time you place a \'9\'',
    type: 'number',
    number: 9,
    effect: 'finisher_momentum',
    cost: 350,
    rarity: 'rare',
  },
  {
    id: 'num_9_l4',
    name: '9 — The Finisher [L4]',
    description: 'Jackpot: Placing the last \'9\' on the board grants a +50 Gold bonus',
    type: 'number',
    number: 9,
    effect: 'finisher_jackpot',
    cost: 550,
    rarity: 'epic',
  },
  {
    id: 'num_9_l5',
    name: '9 — The Finisher [L5]',
    description: 'Head Start: Gain a free Shop Reroll and a 10% discount in the next shop after completing any puzzle',
    type: 'number',
    number: 9,
    effect: 'finisher_head_start',
    cost: 800,
    rarity: 'epic',
  },
  {
    id: 'num_9_rogue',
    name: '9 — The Finisher [ROGUE]',
    description: 'Completionist: When you place the final number of any puzzle, you are offered a free random number upgrade (L1-5) in the next shop',
    type: 'number',
    number: 9,
    effect: 'finisher_completionist',
    cost: 1150,
    rarity: 'rogue',
  },

  {
    id: 'mistake_insurance',
    name: 'Second Chance',
    description: '+2 maximum mistakes',
    type: 'passive',
    effect: 'max_mistakes',
    cost: 80,
    rarity: 'common',
  },
  {
    id: 'corruption_shield',
    name: 'Corruption Shield',
    description: 'Mistakes generate 50% less corruption',
    type: 'passive',
    effect: 'corruption_resist',
    cost: 120,
    rarity: 'rare',
  },
  {
    id: 'golden_touch',
    name: 'Golden Touch',
    description: 'Earn 2x currency this floor',
    type: 'passive',
    effect: 'currency_multiplier',
    cost: 90,
    rarity: 'common',
  },
  {
    id: 'insight_marker',
    name: 'Insight Marker',
    description: 'Mark one ambiguous cell. Wrong guesses in marked cells cause 50% less corruption',
    type: 'consumable',
    effect: 'ambiguity_hedge',
    cost: 80,
    rarity: 'common',
  },
  {
    id: 'truth_beacon',
    name: 'Truth Beacon',
    description: 'Resolve one ambiguous zone per floor. Reveals correct values',
    type: 'consumable',
    effect: 'ambiguity_resolve',
    cost: 120,
    rarity: 'rare',
  },
  {
    id: 'entropy_lens',
    name: 'Entropy Lens',
    description: 'Highlights all ambiguous zones on the board',
    type: 'passive',
    effect: 'ambiguity_detect',
    cost: 70,
    rarity: 'common',
  },
  {
    id: 'divergence_charm',
    name: 'Divergence Charm',
    description: 'Wrong guesses in ambiguous cells only corrupt that cell',
    type: 'passive',
    effect: 'ambiguity_contain',
    cost: 140,
    rarity: 'rare',
  },
  {
    id: 'logic_anchor',
    name: 'Logic Anchor',
    description: 'One row or column becomes ambiguity-free this floor',
    type: 'consumable',
    effect: 'ambiguity_suppress',
    cost: 100,
    rarity: 'rare',
  },
  {
    id: 'purification_ritual',
    name: 'Purification Ritual',
    description: 'Cleanse 5 most corrupted cells immediately',
    type: 'consumable',
    effect: 'cleanse_cells',
    cost: 110,
    rarity: 'rare',
    charges: 1,
    maxCharges: 1,
  },
  {
    id: 'corruption_barrier',
    name: 'Corruption Barrier',
    description: 'Corruption cannot spread this floor',
    type: 'passive',
    effect: 'no_spread',
    cost: 130,
    rarity: 'rare',
  },
  {
    id: 'decay_immunity',
    name: 'Decay Immunity',
    description: 'Corruption degradation effects reduced by 75%',
    type: 'passive',
    effect: 'degradation_resist',
    cost: 100,
    rarity: 'rare',
  },
];

export function getRandomUpgrades(count: number, excludeIds: string[] = []): Upgrade[] {
  const available = UPGRADE_POOL.filter(u => !excludeIds.includes(u.id));
  const shuffled = [...available].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
